-- ============================================================
-- Migration 041: Create leod_reports for post-event report archival
-- ============================================================
-- Reports generated by Agent 3 (Report Generator) are currently
-- ephemeral. This table persists them for audit and review.
-- ============================================================

CREATE TABLE IF NOT EXISTS leod_reports (
  id          UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
  event_id    UUID        REFERENCES leod_events(id) ON DELETE SET NULL,
  generated_by UUID,
  report_data JSONB       NOT NULL DEFAULT '{}',
  created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_reports_event ON leod_reports (event_id, created_at DESC);

ALTER TABLE leod_reports ENABLE ROW LEVEL SECURITY;

-- Directors can read reports for their own events
CREATE POLICY owner_read_reports ON leod_reports
  FOR SELECT TO authenticated
  USING (
    event_id IN (
      SELECT id FROM leod_events
      WHERE created_by = auth.uid()
         OR created_by IN (
           SELECT invited_by FROM leod_users
           WHERE leod_users.id = auth.uid() AND invited_by IS NOT NULL
         )
    )
  );

-- Authenticated users can insert reports
CREATE POLICY auth_insert_reports ON leod_reports
  FOR INSERT TO authenticated
  WITH CHECK (auth.role() = 'authenticated');
